# permissions for end users to view alertchannels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertchannel-viewer-role
rules:
- apiGroups:
  - alerts.k8s.newrelic.com
  resources:
  - alertchannels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alerts.k8s.newrelic.com
  resources:
  - alertchannels/status
  verbs:
  - get
